### PR TITLE
Update docs

### PR DESCRIPTION
**Pull request by mirca**
Hello everyone,

I'm looking into `saba` to see how it can be used to implement some critical features for the new PSF Photometry machinery in `photutils`, more precisely, to use `saba` to compute uncertainties for the PSF fittings. 

In the meantime, I'm improving a little bit the current documentation by placing actual plot directives rather than including the figures in the git repo - I think that's the current behavior in most (all?) `astropy` subpackages.

In addition, I found that when building the docs locally the figure `example_plot_2d_fit.png` does not quite match the current one the online docs.
example_plot_2d_fit

Cheers

### CODE REVIEW

**Comment by nocturnalastro** [comment]
Hey @mirca,
The figures themselves shouldn't be in the repo I though I had gitignored the _generated dir perhaps I forgot to remove them.
I couldn't agree more, about the plot directives. The gen_plots script (which runs on the docs build) was only meant to be a stop gap to get something up - which I could go back and replace when I had time. Unfortunately thesis writing is kicking my ass so I haven't be able to so thanks for starting that off it is most appreciated.

Glad to hear that your looking at `saba`. 
Cheers,
Micky

**Comment by nocturnalastro** [comment]
@mirca  I assume you're finished with this stuff? If so I'll merge :)

**Comment by mirca** [comment]
@nocturnalastro Actually, I will take a look at this before you merge it. Does that sound good?

**Comment by nocturnalastro** [comment]
@mirca That's fine :) Just let me know when your done.

**Comment by mirca** [comment]
@nocturnalastro Once travis passes, I think this is good to go :)

**Comment by nocturnalastro** [comment]
@mirca  Thanks :)

**Pull request merged**
